### PR TITLE
Only start constellation if $ENABLE_CONSTELLATION env var is set

### PR DESCRIPTION
**Pull request by esanchma**
Fixes https://tree.taiga.io/project/marcossanlab-alastria-platform/task/252

### CODE REVIEW

**Comment by marcossanlab** [comment]
When I try to start the node raises this error without ENABLE_CONSTELLATION variable:

```
root@3c7937f27975:~/alastria-node/scripts# ./start.sh
Optional use for a clean start: start clean
./start.sh: line 49: syntax error in conditional expression
```

**Comment by esanchma** [comment]
@marcossanlab This works for me. Please give a try to this branch.

**Comment by marcossanlab** [comment]
In Ubuntu 16.04, if i start with `--watch` flag, when i use ^C for stop `tail -100f`, it also stops geth.

```
root@3762d932ed6b:~/alastria-node/scripts# ENABLE_CONSTELLATION=true ./start.sh --watch
[*] Starting Constellation node
[*] constellation node at 9000 is still starting. Awaiting 5 seconds.
[*] constellation node at 9000 is still starting. Awaiting 5 seconds.
[*] constellation node at 9000 is now up.
[*] resuming start procedure
[*] Starting quorum node
nohup: appending output to 'nohup.out'
INFO [07-04|12:36:17] Starting peer-to-peer node               instance=Geth/REG_EventoBlockchain_2_4_00/v1.7.2-stable-94e1e31e/linux-amd64/go1.9.5
INFO [07-04|12:36:17] Allocated cache and file handles         database=/root/alastria/data/geth/chaindata cache=128 handles=1024
INFO [07-04|12:36:17] Initialised chain configuration          config="{ChainID: <nil> Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: <nil> IsQuorum: true Engine: istanbul}"
INFO [07-04|12:36:17] Initialising Ethereum protocol           versions="[63 62]" network=82584648528
INFO [07-04|12:36:17] Loaded most recent local header          number=0 hash=77a8c9…dd474c td=1
INFO [07-04|12:36:17] Loaded most recent local full block      number=0 hash=77a8c9…dd474c td=1
INFO [07-04|12:36:17] Loaded most recent local fast block      number=0 hash=77a8c9…dd474c td=1
INFO [07-04|12:36:17] Loaded local transaction journal         transactions=0 dropped=0
INFO [07-04|12:36:17] Regenerated local transaction journal    transactions=0 accounts=0
INFO [07-04|12:36:17] Starting P2P networking
INFO [07-04|12:36:19] UDP listener up                          self=enode://3a0bcda0a7a2d3601c9d5fa41c3b86dd58814db6b6ea0cf1aa72b06a443391456fef1a2f4223256008514ebdcbdaf548d7d5eb2ed8e7213449b4f559ca648453@[::]:21000
INFO [07-04|12:36:19] RLPx listener up                         self=enode://3a0bcda0a7a2d3601c9d5fa41c3b86dd58814db6b6ea0cf1aa72b06a443391456fef1a2f4223256008514ebdcbdaf548d7d5eb2ed8e7213449b4f559ca648453@[::]:21000
INFO [07-04|12:36:19] Stats daemon started
INFO [07-04|12:36:19] HTTP endpoint opened: http://0.0.0.0:22000
INFO [07-04|12:36:19] IPC endpoint opened: /root/alastria/data/geth.ipc
^C
root@3762d932ed6b:~/alastria-node/scripts# ps
  PID TTY          TIME CMD
    1 ?        00:00:00 bash
12032 ?        00:00:35 constellation-n
12250 ?        00:00:00 ps
root@3762d932ed6b:~/alastria-node/scripts#
```

**Comment by esanchma** [comment]
The watch option is a start artifact to support docker run and docker logging, and in that context, sigkill should force a complete shutdown. Do you want start&watch to survive ^C ?

**Pull request merged**
