### PR TITLE
Add DXC new nodes data for deployment

### PR DESCRIPTION
**Pull request by miguel-briales**
Added information for regular and validator node to deploy DXC nodes.

### CODE REVIEW

**Comment by go2chain** [comment]
Good Morning,

I was checking the Pull Request and I realized that the constellation-nodes.json file for the regular node has not yet been modified. You can complete that information please.

Thank you.

**Comment by miguel-briales** [comment]
Good morning, we deployed the regular node without constellation. Is it mandatory anyway?

Thank you in advance,
Miguel

**Comment by go2chain** [comment]
Good Morning @miguel-briales ,

It's not mandatory. But nevertheless in the file DIRECTORY_REGULAR you have indicated the column of the key of constellation. Either you do not have a constellation key, or you must indicate the constellation-nodes.json file.

Greetings and many thanks in advance.

**Comment by miguel-briales** [comment]
Thank you, I will update it and let you know asap.

Best regards,
Miguel

**Comment by miguel-briales** [comment]
@go2chain, constellation-nodes.json have been updated.

Thank you in advance

**Comment by go2chain** [comment]
@miguel-briales ,
I see you're still making modifications to the PR files. You can let me know when it's completely finished.

I see that there are several IPs in the constellation-nodes when only the regular one should be there.

If you have any doubt do not hesitate to connect to the Slack we have for Alastria and where we can maintain a more fluid conversation.

[slack](https://github.com/alastria/alastria-node/wiki/HELP)

Thanks

**Comment by miguel-briales** [comment]
Solved all conflicts caused by previous nodes information addition (from other companies -Nodalblock and Flash Telecom-.

**Comment by miguel-briales** [comment]
@go2chain, I have finished, I was updating to solve the conflicts due to the incorporation of Nodalblock and Flash Telecom information.

Many thanks,
Miguel

**Comment by miguel-briales** [comment]
Hi @go2chain, sorry for the inconvenience, I think that now is everything right. Could you check it, please?

Thank you very much,
Miguel

**Comment by go2chain** [comment]
Perfect!

Thank you very much.

**Pull request merged**
