### PR TITLE
Enable api rpc via websocket

### PR DESCRIPTION
**Pull request by rdemera**
I your node got the proxy configuration (Alastria Open Access) you should make a few changes on the nginx conf.

### CODE REVIEW

**Comment by javaguirre** [comment]
There is a small conflict, can you fix it please? Thanks! 💯

**Comment by javaguirre** [comment]
Actually, this is pretty old, should we close it instead?

**Comment by rdemera** [comment]
We got that issue long time ago, i dont really know if others had the same issue, so is up to you. I can resolve the conflicts if you want

**Comment by javaguirre** [comment]
I'll close it then till someone has it again, Thank you @rdemera

**Pull request closed without merging**
